export APP_DIR=/path/to/someapplication/source/code/    # flutter application source code
export BOLT_NAME=flutter.app.someapplication-debug      # bolt name
export STB_IP=1.2.3.4                                   # device ip
export FLUTTER_APP=someapplication-debug                # yocto recipe
export OE_DOWNLOADS=/path/to/downloads                  # yocto downloads folder
export OE_SSTATE_PATH=/path/to/sstate-cache             # yocto sstate cache folder
